version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - public-net

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://database:27017/tasks
    ports:
      - "5000:5000"
    networks:
      - public-net
      - private-net

  database:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks:
      - private-net

networks:
  public-net:
  private-net:

volumes:
  db-data:
